Create the mentor card component
sef-global/scholarx-frontend pull request #11
Opened 2023-07-15 15:07 UTC by anjula-sack

## Purpose

- The purpose of this PR is to fix #6 

## Goals

- To create the mentor card 

## Approach

- Create mentor card component
- Create the story
- Configure the interactions addon
- Add the tests
- Update the github workflows

## Screenshots

<img width="279" alt="Screenshot 2023-07-15 at 8 36 40 PM" src="https://github.com/sef-global/scholarx-frontend/assets/43912578/80c57010-364e-4a30-b150-7ebf5b6e866a">

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2023-07-15 16:01 UTC, Piumal1999 requested changes
Good job @anjula-sack! I requested a minor change.

2023-07-15 16:01 UTC, Piumal1999 commented on src/components/MentorCard/MentorCard.component.tsx
> +      <Text type="secondary">Google Inc</Text>
```suggestion
      <Text type="secondary">{mentor.application.company_or_institution}</Text>
```

2023-07-15 16:01 UTC, Piumal1999 commented on src/components/MentorList/MentorList.stories.ts
> +    mentors: [...mentors, ...mentors],
This is ok for now. But I think there might be a way to generate dummy data when using storybook. Something similar to [FakerJs](https://fakerjs.dev/)?

2023-07-16 04:21 UTC, anjula-sack commented on src/components/MentorList/MentorList.stories.ts
> +    mentors: [...mentors, ...mentors],
This generates only specific fields if we can generate whole objects that's better.

2023-07-20 09:13 UTC, Piumal1999 approved these changes

2023-07-20 09:13 UTC, merged