Show mentees under the mentor profile
sef-global/scholarx-frontend pull request #152
Opened 2024-08-09 14:35 UTC by Madhawa97

Fixes #150

## Purpose

The purpose of this PR is to fix #<issue-number>

## Goals

## Approach

## Screenshots

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2024-08-09 15:30 UTC, anjula-sack commented
It's not just the profile picture. A mentee card should be shown just like we show for the mentors. @Madhawa97 clicking a mentee card should redirect to a public mentee page

2024-08-10 12:57 UTC, Madhawa97 commented
@anjula-sack, Also I've added the pending application count as follows,
 
![image](https://github.com/user-attachments/assets/e5fa97d8-4b4d-4909-a1e1-f37686b08a9b)

2024-08-14 15:21 UTC, anjula-sack requested changes

2024-08-14 15:21 UTC, anjula-sack commented on src/components/ProfilePic/index.tsx
> +};
```suggestion
  
  if(isError || !src) {
   return (
    <div
      style={{ height: size, width: size }}
      className="inline-block bg-gray-200 rounded-full ring-2 ring-white flex items-center justify-center"
    >
      <UserIcon />
    </div>
  ) 
  }

  return (
    <img
      src={src}
      alt={alt}
      className="inline-block rounded-full ring-2 ring-white"
      style={{ height: size, width: size }}
      referrerPolicy="no-referrer"
      onError={() => {
        setIsError(true);
      }}
    />
  );
};
```

2024-08-17 03:54 UTC, anjula-sack approved these changes
Good job! @Madhawa97

2024-08-17 03:54 UTC, merged

2024-08-17 11:09 UTC, Madhawa97 commented
Thanks! @anjula-sack