Add pagination support for the public mentors page
sef-global/scholarx-frontend pull request #182
Opened 2024-09-06 11:33 UTC by Madhawa97

## Purpose

The purpose of this PR is to fix #181

## Goals

## Approach

## Screenshots

##  Checklist
- [ ] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2024-09-08 07:55 UTC, anjula-sack requested changes

2024-09-08 07:55 UTC, anjula-sack commented on src/pages/Mentors/index.tsx
> +  } = useCategories(pageSize);
Remove pagination for this @Madhawa97

2024-09-08 14:33 UTC, anjula-sack requested changes

2024-09-08 14:33 UTC, anjula-sack commented on src/pages/MenteeRegistration/index.tsx
> +            {'An error occurred. Please try again later.'}
```suggestion
            An error occurred. Please try again later.
```

2024-09-09 14:31 UTC, Madhawa97 commented
Updated to match with backend pagination removal for `categories`

2024-09-09 14:47 UTC, anjula-sack commented
> Updated to match with backend pagination removal for `categories`
> 
> We may need a new approach to get the `Total Mentee Slots: X` count in the admin mentor applications page. Also the `totalItemCount` sends when filtered by category seems wrong and should be fixed in the backend. @anjula-sack

Can you create an issue for this?

2024-09-09 14:54 UTC, anjula-sack approved these changes

2024-09-09 14:54 UTC, merged