Added Horizontal Mentor card
sef-global/scholarx-frontend pull request #197
Opened 2024-09-30 16:12 UTC by dilankavishka

## Purpose

The purpose of this PR is to fix #105 

## Goals
This PR introduces a separate component for the mentor card in horizontal view, as opposed to keeping it inside the MentorProfile component. The goal is to improve reusability across the project and maintain cleaner code.

## Approach
* Created a new, reusable MentorCardHorizontal component.

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [-] I have commented my code, particularly in hard-to-understand areas
- [-] I have made corresponding changes to the documentation

2024-10-04 13:06 UTC, anjula-sack commented
can you add a screenshot? Also the pipeline is failing @dilankavishka

2024-10-17 06:59 UTC, dilankavishka commented
@anjula-sack, I did the changes

2024-10-26 13:50 UTC, anjula-sack requested changes

2024-10-26 13:50 UTC, anjula-sack commented on src/components/MenteeApplication/MenteeApplication.component.tsx
> +                </MentorCardHorizontal>
```suggestion
                <MentorCard mentor={mentee?.mentor} />
```

2024-10-26 13:50 UTC, anjula-sack commented on src/components/MentorCardHorizontal/MentorCardHorizontal.component.tsx
> +        >
Link to the mentor page

2024-10-26 13:50 UTC, anjula-sack commented on src/components/MentorCardHorizontal/MentorCardHorizontal.component.tsx
> +  mentor: Mentor|undefined;
```suggestion
  mentor?: Mentor;
```

2024-12-01 07:18 UTC, closed without merging