Enhance Mentor Filter Functionality
sef-global/scholarx-frontend pull request #226
Opened 2024-11-28 17:45 UTC by rdwaynedehoedt

## Purpose
The purpose of this PR is to fix #223. This PR introduces a feature to filter mentors by country, available slots, and category, while also providing sorting functionality. It addresses the need for improved mentor filtering and sorting on the Mentor page.

## Goals
- Implement mentor filtering by country and available slots.

## Approach
This feature was implemented by:
1. Fetching mentors and their associated countries and available slots.
2. Adding state for the selected filters (country, available slots, and category).
3. Implementing checkboxes for users to filter mentors based on selected countries and available slots.
4. Adding dynamic dropdowns that expand/collapse when clicking on filter options.
5. Implementing the sorting function to sort mentors alphabetically by their first name.
6. Ensuring the mentor list updates based on the selected filters using `useEffect` hooks.

The logic for available slots ensures that mentors with no available slots (after considering approved mentees) are excluded from the list unless selected by the user. 

## Screenshots
<img width="1440" alt="Screenshot 2024-11-28 at 23 13 35" src="https://github.com/user-attachments/assets/a85f61ec-69e2-4166-abfa-7e2ab47889ac">

## Checklist
- [ ] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines (http://bit.ly/sef-best-practices)
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
- OS: macOS
- Browser: Chrome

## Learning
- To implement the filtering and sorting functionality, I used React hooks such as `useState`, `useEffect`, and `useInView` for infinite scroll.
- I researched and implemented the dynamic dropdown functionality using conditional rendering to ensure smooth user interaction.

2024-11-29 14:12 UTC, anjula-sack requested changes

2024-11-29 14:12 UTC, anjula-sack commented on src/pages/Mentors/index.tsx
> +        .map((mentor) => {
can you check mentor.application object for the availableSlots and approvedMenteesCount. It should be there. @rdwaynedehoedt

2024-11-29 14:12 UTC, anjula-sack commented on src/pages/Mentors/index.tsx
> +          const approvedMenteesCount = mentor?.mentees
Same here.

2024-11-29 14:12 UTC, anjula-sack commented on src/pages/Mentors/index.tsx
> -      a.application.firstName.localeCompare(b.application.firstName)
What's the issue here?

2024-11-29 14:17 UTC, anjula-sack requested changes

2024-11-29 14:17 UTC, anjula-sack commented on src/pages/Mentors/index.tsx
> +                      {slots} Slots Available
Slots should be a slider like this,

<img width="319" alt="image" src="https://github.com/user-attachments/assets/8d88aaf0-abab-499e-b8a2-8b8ac051021f">

2024-12-21 10:01 UTC, rdwaynedehoedt commented
@anjula-sack  Please review and approve the PR.

2024-12-21 14:35 UTC, anjula-sack requested changes

2024-12-21 14:35 UTC, anjula-sack commented on package.json
> +    "@mui/material": "^6.1.10",
Do we need to use material here?

2025-01-04 08:25 UTC, closed without merging