The purpose of this PR is to fix the positioning issue of the Facebook icon and the Apply button.
sef-global/scholarx-frontend pull request #68
Opened 2024-01-09 18:27 UTC by mayura-andrew

## Purpose

The purpose of this PR is to fix #65 

## Goals

The goal is to improve the user interface by fixing the positioning of the Facebook icon and the Apply button.

## Approach

The approach taken was to modify the CSS styles of the Facebook icon and the Apply button.

## Screenshots

![Screenshot_20240109_234644-1](https://github.com/sef-global/scholarx-frontend/assets/48531182/0a473fbf-850e-4001-9f08-7180168c4cbf)

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Related PRs
 
N/A

## Test environment
 
OS - Fedora Linux 39 (KDE Plasma) x86_64
NodeJS - 20.10.0

## Learning

N/A

2024-01-10 15:24 UTC, anjula-sack requested changes

2024-01-10 15:24 UTC, anjula-sack commented on src/components/Home/Home.tsx
> +            }}
Let's use tailwind css here @mayura-andrew

2024-01-10 15:32 UTC, mayura-andrew commented on src/components/Home/Home.tsx
> +            }}
okay sure

2024-01-10 17:50 UTC, mayura-andrew commented on src/components/Home/Home.tsx
> +            }}
https://github.com/sef-global/scholarx-frontend/assets/48531182/1d9bdfb1-a8f4-4a23-a51c-6435417cf8aa

2024-01-11 03:29 UTC, anjula-sack requested changes

2024-01-11 03:29 UTC, anjula-sack commented on src/components/Home/Home.tsx
> +              className={`flex justify-center items-center mr-5 mb-5 text-black py-1 px-16 rounded w-40 h-9 font-sans font-bold`}
We don't need template literals here.

```suggestion
              className="flex justify-center items-center mr-5 mb-5 text-black py-1 px-16 rounded w-40 h-9 font-sans font-bold"
```

2024-01-11 03:29 UTC, anjula-sack commented on src/components/Home/Home.tsx
> +              className={`flex justify-center items-center mr-5 mb-5 bg-blue-500 hover:bg-blue-700 text-white py-1 px-16 rounded w-40 h-9 font-sans font-bold`}
```suggestion
              className="flex justify-center items-center mr-5 mb-5 bg-blue-500 hover:bg-blue-700 text-white py-1 px-16 rounded w-40 h-9 font-sans font-bold"
```

2024-01-11 04:00 UTC, mayura-andrew commented on src/components/Home/Home.tsx
> +              className={`flex justify-center items-center mr-5 mb-5 text-black py-1 px-16 rounded w-40 h-9 font-sans font-bold`}
Ok got it 👍

2024-01-11 06:18 UTC, anjula-sack approved these changes
Good job! @mayura-andrew

2024-01-11 06:18 UTC, merged

2024-01-11 06:23 UTC, mayura-andrew commented
Thank you :)