add tailwind to mainLayOut and NavBar
sef-global/scholarx-frontend pull request #75
Opened 2024-01-31 12:50 UTC by kavinda-100

## Purpose
The Navbar is not responsive when resizing the browser window.
(https://github.com/sef-global/scholarx-frontend/issues/73)

## Goals
add tailwindcss utility classes to MainLayOut and NavBar to fix the issue.

## Approach
 I had set the max width to the nav bar and added proper Tailwind classes according to the device breakpoints to achieve responsiveness for the NavBar.

## Screenshots
https://github.com/sef-global/scholarx-frontend/issues/73#issuecomment-1904086007

##  Checklist
- [ ] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2024-01-31 12:55 UTC, kavinda-100 commented
add tailwind branch

2024-01-31 17:26 UTC, anjula-sack requested changes

2024-01-31 17:26 UTC, anjula-sack commented on src/components/Layout/MainLayout.tsx
> +// import styles from './MainLayout.module.css';
```suggestion
```

2024-01-31 17:26 UTC, anjula-sack commented on src/components/Layout/Navbar/Navbar.tsx
> +                <Text className="antTypography text-primary text-[14px] font-light">Join Us</Text>
Use a standard size like `text-sm` `text-md`

2024-01-31 17:26 UTC, anjula-sack commented on tailwind.config.js
> +      'ant-icon-color': '#525F7F',
Lets use a different name here without the ant part

```suggestion
      'ant-icon-color': '#525F7F',
```

2024-02-05 15:11 UTC, anjula-sack commented
@kavinda-100 There are some conflicts can you fix them?

2024-02-12 13:22 UTC, anjula-sack commented
@kavinda-100 There are some conflicts can you fix them as well?

2024-02-12 13:27 UTC, kavinda-100 commented
done the required changes

2024-02-12 13:28 UTC, anjula-sack commented
@kavinda-100 The conflicts are still there

2024-03-02 13:57 UTC, anjula-sack requested changes
@mayura-andrew There are some lint issues.

2024-04-17 05:28 UTC, anjula-sack commented
Closing due to inactivity

2024-04-17 05:29 UTC, closed without merging