Change components from ant design to tailwind css
sef-global/scholarx-frontend pull request #78
Opened 2024-02-02 19:48 UTC by RandilaP

## Purpose
The goal of this PR is to remove ant design and change it to the tailwind css

The purpose of this PR is to fix #<issue-number>

## Goals

## Approach

## Screenshots

##  Checklist
- [ ] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2024-02-03 07:00 UTC, anjula-sack requested changes

2024-02-03 07:00 UTC, anjula-sack commented on src/components/Testimonials/TestimonialCard.tsx
> -      className={styles.testimonialCardImage}
Can you remove the css files as well? Also remove antd library as well.

2024-02-06 07:12 UTC, RandilaP commented
@anjula-sack Could you please review this

2024-02-06 09:57 UTC, anjula-sack approved these changes
Good job! @RandilaP

2024-02-06 09:57 UTC, merged