Implementation of the Google OAuth on the frontend
sef-global/scholarx-frontend pull request #80
Opened 2024-02-08 17:00 UTC by mayura-andrew

## Purpose

The purpose of this PR is to fix #77
## Goals
Implemented Google Sign-in button in the LoginModal Component to enhance user experience and ease of login.

## Approach
Integrated Google's OAuth API to handle authentication and incorporated the Google Sign-In button into the LoginModal component. Users can now sign in using their Google accounts.

## Screenshots
![Screenshot_20240208_222432](https://github.com/sef-global/scholarx-frontend/assets/48531182/a73a8932-4cc7-499a-966c-6a7205c965c0)

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Related PRs

## Test environment
Web Browser - Vivaldi 6.5.3206.59 stable
NodeJs - v20.10.0

## Learning
Learned about Google's OAuth implementation in frontend. This feature will help users to login quickly using their Google account credentials, improving the overall user experience.

2024-02-10 13:55 UTC, anjula-sack requested changes

2024-02-10 13:55 UTC, anjula-sack commented on src/components/LoginModal/index.tsx
> +                  style={{ margin: '0' }}
```suggestion
```
m-0

2024-02-11 13:03 UTC, anjula-sack commented
Hi @mayura-andrew, can you add the requested change?

2024-02-11 15:05 UTC, mayura-andrew commented
Year sure I will it tonight

2024-02-11 16:19 UTC, anjula-sack approved these changes
Good job! @mayura-andrew

2024-02-11 16:19 UTC, merged