mplement MyMenteesView Component for Mentor Dashboard
sef-global/scholarx-frontend pull request #86
Opened 2024-02-24 16:31 UTC by udeesha-kularathne

## Purpose
The purpose of this PR is to address issue #20 by implementing the functionality of the MyMenteesView component.

## Goals
Implement a new component to manage and display mentee applications.

Ensure responsive design for optimal viewing on both mobile and desktop devices.

Enhance user experience by providing detailed applicant information in a user-friendly layout.

Address specific issues outlined in #20 - Mentor Dashboard - MyMenteesView

## Approach

The MyMentees component was developed to manage mentee applications.

Implemented conditional rendering to display applicant details upon selection.

## Screenshots
![MyMenteesView_PR1](https://github.com/sef-global/scholarx-frontend/assets/45477393/c5c2ebe8-2e80-4b44-ac6d-f2d109318029)

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2024-02-24 17:08 UTC, anjula-sack requested changes

2024-02-24 17:08 UTC, anjula-sack commented on src/components/MyMenteesView/MyMentees.component.tsx
> +              style={{ fontSize: '28px', fontWeight: '600' }}
Shall we use taliwind here? ex: font-md font-semibold

2024-02-24 17:08 UTC, anjula-sack commented on src/components/MyMenteesView/MyMentees.component.tsx
> +            <span style={{ fontSize: '48px' }}>&#8592;</span>
Here as well

2024-02-24 17:09 UTC, udeesha-kularathne commented on src/components/MyMenteesView/MyMentees.component.tsx
> +            <span style={{ fontSize: '48px' }}>&#8592;</span>
Okay i'll change it

2024-02-25 05:04 UTC, anjula-sack requested changes, later dismissed
Requested a small change

2024-02-25 05:04 UTC, anjula-sack commented on src/components/MyMenteesView/MyMentees.component.tsx
> +    console.log('Back button clicked');
Lets remove this log

2024-02-25 07:53 UTC, udeesha-kularathne commented on src/components/MyMenteesView/MyMentees.component.tsx
> +    console.log('Back button clicked');
Okay. i removed it

2024-02-25 08:43 UTC, merged

2024-02-25 08:43 UTC, anjula-sack commented
Good job @udeesha-kularathne!